### ISSUE TITLE
greenscript should use play configuration file

### ISSUE THREAD

**Issue by FroMage** [greenlaw110/play-greenscript#1]
Hello,

Thanks for greenscript, it's very useful, but a bit annoying to put in prod with different configuration from dev. In Play! applications should put their configuration in application.conf, which allows users to specify different configuration based on framework ID (one for dev, one for prod) as such:

gs.minimize.enabled=false
gs.nocache=true
gs.compress=false

%prod.gs.minimize.enabled=true
%prod.gs.nocache=false
%prod.gs.compress=true

You should use Play!'s application.conf with a greenscript prefix, and load it from your Plugin's onConfigurationRead method, this would make it more standard and easy to deploy. Thanks.

**Comment by greenlaw110** [comment]
Good comment. Will get it done in next version

**Comment by greenlaw110** [comment]
fixed in v1.1
