### ISSUE TITLE
why not providing a greenscript tag for inline JS scripting?

### ISSUE THREAD

**Issue by mandubian** [greenlaw110/play-greenscript#2]
hello,
I was wondering if it would be a good idea to allow declaring inline javascript and your module is in charge of pasting the <script> into <head>.
For ex:
    {greenscript.inlinejs}
    // do something in javascript
        var myvar=0;
    function myfunc(myparam1){
      // blabla
    }
    {/greenscript.inlinejs}

This is just a idea...

best regards
Pascal Voitot

**Comment by greenlaw110** [comment]
Hey, nice idea! thx buddy :)

**Comment by greenlaw110** [comment]
This is implemented on Play-greenscript v1.2 . See http://www.playframework.org/modules/greenscript-1.2/home.
